# Generated by Django 3.2.4 on 2021-07-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='haha',
            field=models.CharField(default=11, max_length=20),
            preserve_default=False,
        ),
    ]
