# Generated by Django 3.2.4 on 2021-07-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_haha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='haha',
        ),
    ]
