# Generated by Django 3.2.4 on 2021-07-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subbank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Subbank_Name',
            new_name='Subbank',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Depart_ID',
            new_name='Depart',
        ),
    ]
