# Generated by Django 3.2.4 on 2021-07-07 08:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('subbank', '0002_auto_20210707_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Money', models.DecimalField(decimal_places=2, max_digits=20)),
                ('slug', models.SlugField()),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('Subbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_by', to='subbank.subbank')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_loan', to='user.user')),
            ],
            options={
                'ordering': ['-CreatedDate'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PayDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('PayMoney', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays_for', to='loan.loan')),
            ],
        ),
    ]
