# Generated by Django 3.2.4 on 2021-07-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subbank', '0002_auto_20210707_0829'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='Manager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_for', to='subbank.employee'),
            preserve_default=False,
        ),
    ]
