# Generated by Django 3.2.4 on 2021-07-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loan_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='slug',
        ),
    ]
