# Generated by Django 3.2.4 on 2021-07-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_auto_20210708_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='CreatedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='PayDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
